SELECT TOP (1000) [Name]
      ,[Full_Address]
      ,[Contact]
      ,[Age]
      ,[Gender]
      ,[Blood_Group]
      ,[Major_Disease]
      ,[pid]
      ,[P_Password]
      ,[email]
  FROM [Hospital Management System].[dbo].[AddPatient]
